import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart


def send_email_alert(changes, smtp_config, email_from, email_to):
    if not changes:
        return

    subject = "[Easy Price Monitor] Alert: Price Change Detected"
    body = (
        "Hello,\n\n"
        "Easy Price Monitor has detected changes in the prices of your monitored products:\n\n"
    )
    changed_products = [
        f"<li>{c['product_name']} at {c['shop_name']}: "
        f"New price: {c['price']} (change: {c['price_diff']})</li>"
        for c in changes
    ]
    changed_products = "".join(changed_products)

    #body += "Best regards,\nThe Easy Price Monitor \n Message generated by Easy Price Monitor, please do not reply."

    msg = MIMEMultipart()
    msg["From"] = email_from
    msg["To"] = email_to
    msg["Subject"] = subject
    msg.set_content('''
        <!DOCTYPE html>
        <html>
        <head>
            <link rel="stylesheet" type="text/css" hs-webfonts="true" href="https://fonts.googleapis.com/css?family=Lato%7CLato:i,b,bi">
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <style type="text/css">
              h1{font-size:56px}
              h2{font-size:28px;font-weight:900}
              p{font-weight:100}
              td{vertical-align:top}
              #email{margin:auto;width:600px;background-color:#fff}
            </style>
        </head>
        <body bgcolor="#F5F8FA" style="width: 100%; font-family:Lato, sans-serif; font-size:18px;">
        <div id="email">
            <table role="presentation" width="100%">
                <tr>
                    <td bgcolor="#00A4BD" align="center" style="color: white;">
                        <h1> Products price change detected!</h1>
                    </td>
            </table>
            <table role="presentation" border="0" cellpadding="0" cellspacing="10px" style="padding: 30px 30px 30px 60px;">
                <tr>
                    <td>
                        <h2>Easy Price Monitor has detected changes in the prices of your monitored products:</h2>
                       <ul>{changed_products}</ul>
                    </td>
                </tr>
            </table>
        </div>
        </body>
        </html>
    '''.format(changed_products=changed_products), subtype='html')
    # msg.attach(MIMEText(body, "plain"))

    with smtplib.SMTP(smtp_config["server"], smtp_config["port"]) as server:
        server.starttls()
        server.login(smtp_config["user"], smtp_config["password"])
        server.send_message(msg)

