import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from storage import get_product_url_by_id_mysql, get_shop_id_by_name_mysql


def send_email_alert(changes, smtp_config, email_from, email_to):
    if not changes:
        return

    from datetime import datetime
    
    subject = "[Easy Price Monitor] Alert: Price Change Detected"
    changed_products = []

    for c in changes:
        url = get_product_url_by_id_mysql(c['product_id'], get_shop_id_by_name_mysql(c['shop_name']))
        changed_products.append(
            f"<li><a href='{url}'>{c['product_name']}</a> at {c['shop_name']}: "
            f"(change: <b>{c['price_diff']} {c['currency']}, {c['percent_change']} % change {'↑' if c['price_diff'] > 0 else '↓' if c['price_diff'] < 0 else '→'})</b>"
            f"<br> Current price <b>{c['price']}</b></li>"
        )

    changed_products = "".join(changed_products)

    msg = MIMEMultipart()
    msg["From"] = email_from
    msg["To"] = email_to
    msg["Subject"] = subject
    body = f"""
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Price Alert</title>
      <style>
        body {{
          margin: 0;
          padding: 0;
          background-color: #f5f8fa;
          font-family: Arial, sans-serif;
          -webkit-text-size-adjust: 100%;
        }}
        .container {{
          max-width: 600px;
          margin: 0 auto;
          background: #ffffff;
          border-radius: 8px;
          overflow: hidden;
          box-shadow: 0 2px 6px rgba(0,0,0,0.1);
        }}
        .header {{
          background: #00A4BD;
          color: #ffffff;
          text-align: center;
          padding: 24px;
        }}
        .header h1 {{
          margin: 0;
          font-size: 24px;
        }}
        .content {{
          padding: 20px;
          color: #333333;
          font-size: 16px;
          line-height: 1.5;
        }}
        .content h2 {{
          font-size: 18px;
          margin-bottom: 12px;
          color: #00A4BD;
        }}
        .product-list li {{
          margin-bottom: 8px;
        }}
        .footer {{
          font-size: 12px;
          color: #888888;
          text-align: center;
          padding: 16px;
        }}
        @media only screen and (max-width: 600px) {{
          .header h1 {{
            font-size: 20px;
          }}
          .content {{
            font-size: 14px;
          }}
        }}
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>🔔 Price Change Detected</h1>
        </div>
        <div class="content">
          <h2>Easy Price Monitor found updates:</h2>
          <ul class="product-list">
            {changed_products}
          </ul>
          <p style="margin-top:20px;">
            Best regards,<br>
            <b>Easy Price Monitor</b><br>
            <span style="font-size:12px; color:#888;">This is an automated message, please do not reply.</span>
          </p>
        </div>
        <div class="footer">
          Generated by <a href="https://github.com/Kordight/Easy-Price-Monitor"> Easy Price Monitor </a>
        </div>
      </div>
    </body>
    </html>
    """

    msg.attach(MIMEText(body, "html"))

    port = smtp_config["port"]
    
    host = smtp_config["server"]
    from datetime import datetime
    try:
        if port == 465:
            # SSL
            print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] [INFO] Connecting to SMTP server {host}:{port} using SSL")
            with smtplib.SMTP_SSL(host, port) as smtp:
                smtp.login(smtp_config["user"], smtp_config["password"])
                smtp.send_message(msg)
        else:
            # STARTTLS
            print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] [INFO] Connecting to SMTP server {host}:{port} using STARTTLS")
            with smtplib.SMTP(host, port) as smtp:
                smtp.ehlo()
                smtp.starttls()
                smtp.ehlo()
                smtp.login(smtp_config["user"], smtp_config["password"])
                smtp.send_message(msg)
        print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] [INFO] Email alert sent successfully to {email_to}")
    except Exception as e:
        print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] [ERROR] Failed to send email to {email_to}: {e}")


