import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart


def send_email_alert(changes, smtp_config, email_from, email_to):
    if not changes:
        return

    subject = "[Easy Price Monitor] Alert: Price Change Detected"
    body = (
        "Hello,\n\n"
        "Easy Price Monitor has detected changes in the prices of your monitored products:\n\n"
    )

    for change in changes:
        body += (
            f"• {change['product_name']} at {change['shop_name']}:\n"
            f"  New price: {change['price']} (change: {change['price_diff']})\n\n"
        )

    body += "Best regards,\nThe Easy Price Monitor \n Message generated by Easy Price Monitor, please do not reply."

    msg = MIMEMultipart()
    msg["From"] = email_from
    msg["To"] = email_to
    msg["Subject"] = subject
    msg.attach(MIMEText(body, "plain"))

    with smtplib.SMTP(smtp_config["server"], smtp_config["port"]) as server:
        server.starttls()
        server.login(smtp_config["user"], smtp_config["password"])
        server.send_message(msg)

